"""Add sizes and colors to Product model

Revision ID: 0c1bfbf39af1
Revises: 5100a97142aa
Create Date: 2025-03-14 17:19:44.416096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1bfbf39af1'
down_revision = '5100a97142aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('colors', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('colors')
        batch_op.drop_column('sizes')

    # ### end Alembic commands ###
